### ISSUE TITLE
Example no longer works with version 5.0

### ISSUE THREAD

**Issue by maebli** [adamgreig/assign-resources#17]
If implement using the example it works with v0.4.1 but not with v0.5 example needs to be updated

**Comment by elizabethshirley** [comment]
+1
Compiler complains `cannot find Peri in this scope`, but there is no Peri in embassy-stm32 to use this.

**Comment by adamgreig** [comment]
The change in 0.5 is from #14 and requires that you use the latest (development) version of Embassy, which has changed the API to use the new Peri types. I think that's probably the issue here. For older versions of Embassy you should be able to keep using 0.4.

**Comment by ismet55555** [comment]
Thanks for the explanation. Is this something that will be fixed or updated?

```toml
[dependencies]
assign-resources = { git = "https://github.com/adamgreig/assign-resources", rev = "bd22cb7a92031fb16f74a5da42469d466c33383e" }
cortex-m = "0.7"
cortex-m-rt = "0.7"
defmt = "1.0"
defmt-rtt = "1.0"
embedded-io-async = { version = "0.6", features = ["defmt-03"] }
fixed = "1.29"
heapless = { version = "0.8", features = ["serde"] }
num-traits = { version = "0.2", default-features = false }
panic-halt = "1.0"
panic-probe = { version = "1.0", features = ["print-defmt"] }
portable-atomic = { version = "1.11", features = ["critical-section"] }
rand = { version = "0.9", default-features = false, features = ["small_rng"] }
reqwless = { version = "0.13", features = ["defmt"] }
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde-json-core = "0.6"                                                                                                        # Downgraded from 0.6 to match working example
static_cell = "2.1"
critical-section = "1.1"                                                                                                       # Added - needed for RP2350

######################################################################
#                    Embassy dependencies
######################################################################
embassy-embedded-hal = { version = "0.3", features = ["defmt"] }
embassy-executor = { version = "0.7", features = [
  "arch-cortex-m",
  "executor-thread",
  "executor-interrupt",
  "defmt",
] }
embassy-rp = { version = "0.4", features = [
  "critical-section-impl",
  "time-driver",
  "defmt",
  "unstable-pac",
  "rp235xb",
  "binary-info",
] }
embassy-time = { version = "0.4", features = [
  "defmt",
  "defmt-timestamp-uptime",
] }
embassy-sync = { version = "0.7", features = ["defmt"] }
embassy-futures = { version = "0.1", features = ["defmt"] }
embassy-net = { version = "0.7", features = [
  "defmt",
  "tcp",
  "udp",
  "raw",
  "dhcpv4",
  "medium-ethernet",
  "dns",
] }
cyw43 = { version = "0.3", features = ["defmt", "firmware-logs"] }
cyw43-pio = { version = "0.4", features = [
  "defmt",
] }

```

```rust
use assign_resources::assign_resources;

.....

assign_resources! {
    buttons: ResourcesButtons {
        button0: PIN_15, // Top Button
    }
    .......
}

```

```txt
error[E0412]: cannot find type `Peri` in this scope
   --> src/main.rs:61:1
    |
61  | / assign_resources! {
62  | |     /// Button hardware resources split
63  | |     buttons: ResourcesButtons {
64  | |         button0: PIN_15, // Top Button
...   |
106 | | }
    | |_^ not found in this scope
    |
    = note: this error originates in the macro `assign_resources` (in Nightly builds, run with -Z macro-backtrace for more info)

```
